services:
  server:
    build:
      context: ./src/
      dockerfile: server.dockerfile
    ports:
      - "1234:1234"
    networks:
      - lan
    volumes:
      - ./logs:/logs:rw
      - ./db:/Drizzle/db:rw

  client:
    build:
      context: ./src/
      dockerfile: client.dockerfile
    ports:
      - "1234:1234"
      - "4321:4321"
    networks:
      - lan
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - ./logs:/logs:rw
      - ./downloads:/Drizzle/downloads:rw
      - ./tmp:/Drizzle/tmp:rw

networks:
  lan:
    name: lan
    driver: bridge
